version: '3.8'

services:
  react:
    container_name: react_dockerize
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "8888:3000"
    command: npm start
